<E2ETraceEvent xmlns="http://schemas.microsoft.com/2004/06/E2ETraceEvent"><System xmlns="http://schemas.microsoft.com/2004/06/windows/eventlog/system"><EventID>0</EventID><Type>3</Type><SubType Name="Error">0</SubType><Level>2</Level><TimeCreated SystemTime="2017-08-10T10:50:33.4519907Z" /><Source Name="Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware" /><Correlation ActivityID="{00000000-0000-0000-0000-000000000000}" /><Execution ProcessName="w3wp" ProcessID="12392" ThreadID="49" /><Channel/><Computer>WUGUOQING</Computer></System><ApplicationData>Authentication failed&#xD;&#xA;System.NullReferenceException: 未将对象引用设置到对象的实例。&#xD;&#xA;   在 Orchard.WebApi.OAuth2.OwinOAuth.Provider.AccessTokenProvider.&lt;&gt;c__DisplayClass6_0.&lt;ReceiveAsync&gt;b__0() 位置 G:\Projects\NET\Framework\Noob\Orchard\src\Modules\Orchard.WebApi.OAuth2\OwinOAuth\Provider\AccessTokenProvider.cs:行号 73&#xD;&#xA;   在 System.Threading.Tasks.Task.Execute()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#xD;&#xA;   在 Orchard.WebApi.OAuth2.OwinOAuth.Provider.AccessTokenProvider.&lt;ReceiveAsync&gt;d__6.MoveNext() 位置 G:\Projects\NET\Framework\Noob\Orchard\src\Modules\Orchard.WebApi.OAuth2\OwinOAuth\Provider\AccessTokenProvider.cs:行号 70&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.&lt;AuthenticateCoreAsync&gt;d__0.MoveNext()</ApplicationData></E2ETraceEvent>